import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations);

  static List<String> languages() =>
      ['en', 'es', 'vi', 'zh_Hans', 'fr', 'hi', 'ar', 'sw', 'ru'];

  String get languageCode => locale.languageCode;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.languageCode] ?? '';

  String getVariableText({
    String enText = '',
    String esText = '',
    String viText = '',
    String zh_HansText = '',
    String frText = '',
    String hiText = '',
    String arText = '',
    String swText = '',
    String ruText = '',
  }) =>
      [
        enText,
        esText,
        viText,
        zh_HansText,
        frText,
        hiText,
        arText,
        swText,
        ruText
      ][languageIndex] ??
      '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.languageCode);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // loginPage
  {
    'zc6cyo0v': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'es': 'Acceso',
      'fr': 'Connexion',
      'hi': 'लॉग इन करें',
      'ru': 'Авторизоваться',
      'sw': 'Ingia',
      'vi': 'Đăng nhập',
      'zh_Hans': '登录',
    },
    '171as67n': {
      'en': 'Email Address',
      'ar': 'عنوان بريد الكتروني',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ru': 'Адрес электронной почты',
      'sw': 'Barua pepe',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    '6n8xhpuy': {
      'en': 'Enter your email...',
      'ar': 'أدخل بريدك الإلكتروني ...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrer votre Email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'ru': 'Введите адрес электронной почты...',
      'sw': 'Weka barua pepe yako...',
      'vi': 'Nhập email của bạn...',
      'zh_Hans': '输入你的电子邮箱...',
    },
    'v4t64rpe': {
      'en': 'Password',
      'ar': 'كلمه السر',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ru': 'Пароль',
      'sw': 'Nenosiri',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
    },
    'ij3vdqec': {
      'en': 'Enter your password...',
      'ar': 'ادخل رقمك السري...',
      'es': 'Ingresa tu contraseña...',
      'fr': 'Tapez votre mot de passe...',
      'hi': 'अपना पासवर्ड डालें...',
      'ru': 'Введите ваш пароль...',
      'sw': 'Weka nenosiri lako...',
      'vi': 'Nhập mật khẩu của bạn...',
      'zh_Hans': '输入您的密码...',
    },
    'wcbq7k5i': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'es': 'Acceso',
      'fr': 'Connexion',
      'hi': 'लॉग इन करें',
      'ru': 'Авторизоваться',
      'sw': 'Ingia',
      'vi': 'Đăng nhập',
      'zh_Hans': '登录',
    },
    'ls0pucc4': {
      'en': 'Forgot Password?',
      'ar': 'هل نسيت كلمة السر؟',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'hi': 'पासवर्ड भूल गए?',
      'ru': 'Забыли пароль?',
      'sw': 'Umesahau nywila?',
      'vi': 'Quên mật khẩu?',
      'zh_Hans': '忘记密码？',
    },
    'vtzcfrkj': {
      'en': 'Chooose Language',
      'ar': 'اختر اللغة',
      'es': 'Elegir idioma',
      'fr': 'Choisissez la langue',
      'hi': 'भाषा चुनें',
      'ru': 'Выберите язык',
      'sw': 'Chagua Lugha',
      'vi': 'Lựa chọn ngôn ngữ',
      'zh_Hans': '选择语言',
    },
    'onnwiqt3': {
      'en': 'Register',
      'ar': 'يسجل',
      'es': 'Registro',
      'fr': 'S&#39;inscrire',
      'hi': 'पंजीकरण करवाना',
      'ru': 'регистр',
      'sw': 'Sajili',
      'vi': 'Đăng ký',
      'zh_Hans': '登记',
    },
    'mtukiwe6': {
      'en': 'Email Address',
      'ar': 'عنوان بريد الكتروني',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ru': 'Адрес электронной почты',
      'sw': 'Barua pepe',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    'ytroea6x': {
      'en': 'Enter your email...',
      'ar': 'أدخل بريدك الإلكتروني ...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrer votre Email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'ru': 'Введите адрес электронной почты...',
      'sw': 'Weka barua pepe yako...',
      'vi': 'Nhập email của bạn...',
      'zh_Hans': '输入你的电子邮箱...',
    },
    'vvrulcid': {
      'en': 'Password',
      'ar': 'كلمه السر',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ru': 'Пароль',
      'sw': 'Nenosiri',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
    },
    '64ngpew2': {
      'en': 'Enter your password...',
      'ar': 'ادخل رقمك السري...',
      'es': 'Ingresa tu contraseña...',
      'fr': 'Tapez votre mot de passe...',
      'hi': 'अपना पासवर्ड डालें...',
      'ru': 'Введите ваш пароль...',
      'sw': 'Weka nenosiri lako...',
      'vi': 'Nhập mật khẩu của bạn...',
      'zh_Hans': '输入您的密码...',
    },
    'dwlfsmt0': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'ru': 'Подтвердить Пароль',
      'sw': 'Thibitisha Nenosiri',
      'vi': 'Xác nhận mật khẩu',
      'zh_Hans': '确认密码',
    },
    '6gv68t5y': {
      'en': 'Enter your password...',
      'ar': 'ادخل رقمك السري...',
      'es': 'Ingresa tu contraseña...',
      'fr': 'Tapez votre mot de passe...',
      'hi': 'अपना पासवर्ड डालें...',
      'ru': 'Введите ваш пароль...',
      'sw': 'Weka nenosiri lako...',
      'vi': 'Nhập mật khẩu của bạn...',
      'zh_Hans': '输入您的密码...',
    },
    'ktf8iijg': {
      'en': 'Create Account',
      'ar': 'إنشاء حساب',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'ru': 'Зарегистрироваться',
      'sw': 'Tengeneza akaunti',
      'vi': 'Tạo tài khoản',
      'zh_Hans': '创建帐号',
    },
    'jgbjl1ti': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // forgotPassword
  {
    '9075ii2u': {
      'en': 'Forgot Password',
      'ar': 'هل نسيت كلمة السر',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'ru': 'Забыли пароль',
      'sw': 'Umesahau nywila',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码',
    },
    'kenycmun': {
      'en':
          'Enter the email associated with your account and we will send you a verification code.',
      'ar': 'أدخل البريد الإلكتروني المرتبط بحسابك وسنرسل لك رمز التحقق.',
      'es':
          'Introduce el correo electrónico asociado a tu cuenta y te enviaremos un código de verificación.',
      'fr':
          'Entrez l&#39;e-mail associé à votre compte et nous vous enverrons un code de vérification.',
      'hi':
          'अपने खाते से संबद्ध ईमेल दर्ज करें और हम आपको एक सत्यापन कोड भेजेंगे।',
      'ru':
          'Введите адрес электронной почты, связанный с вашей учетной записью, и мы вышлем вам код подтверждения.',
      'sw':
          'Ingiza barua pepe inayohusishwa na akaunti yako na tutakutumia nambari ya kuthibitisha.',
      'vi':
          'Nhập email được liên kết với tài khoản của bạn và chúng tôi sẽ gửi cho bạn mã xác minh.',
      'zh_Hans': '输入与您的帐户关联的电子邮件，我们将向您发送验证码。',
    },
    '2y8nzv31': {
      'en': 'Email Address',
      'ar': 'عنوان بريد الكتروني',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ru': 'Адрес электронной почты',
      'sw': 'Barua pepe',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    '8fjt7lrs': {
      'en': 'Enter your email...',
      'ar': 'أدخل بريدك الإلكتروني ...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrer votre Email...',
      'hi': 'अपना ईमेल दर्ज करें...',
      'ru': 'Введите адрес электронной почты...',
      'sw': 'Weka barua pepe yako...',
      'vi': 'Nhập email của bạn...',
      'zh_Hans': '输入你的电子邮箱...',
    },
    'xsldb6ee': {
      'en': 'Send Reset Link',
      'ar': 'أرسل رابط إعادة التعيين',
      'es': 'Enviar enlace de reinicio',
      'fr': 'Envoyer le lien de réinitialisation',
      'hi': 'रीसेट लिंक भेजें',
      'ru': 'Отправить ссылку для сброса',
      'sw': 'Tuma Kiungo cha Kuweka Upya',
      'vi': 'Gửi liên kết đặt lại',
      'zh_Hans': '发送重置链接',
    },
    '0zi87822': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // completeProfile
  {
    'q9rwnij2': {
      'en': 'Complete Profile',
      'ar': 'الملف الشخصي الكامل',
      'es': 'Perfil completo',
      'fr': 'Profil complet',
      'hi': 'पूरा प्रोफाइल',
      'ru': 'Полный профиль',
      'sw': 'Kamilisha Wasifu',
      'vi': 'Hoàn thành hồ sơ',
      'zh_Hans': '完整档案',
    },
    'acr0v5a1': {
      'en': 'Upload a photo for us to easily identify you.',
      'ar': 'قم بتحميل صورة لنا للتعرف عليك بسهولة.',
      'es': 'Sube una foto para que te identifiquemos fácilmente.',
      'fr':
          'Téléchargez une photo pour que nous puissions vous identifier facilement.',
      'hi': 'आसानी से आपकी पहचान करने के लिए हमारे लिए एक फोटो अपलोड करें।',
      'ru': 'Загрузите фото, чтобы мы могли легко вас идентифицировать.',
      'sw': 'Pakia picha ili tukutambue kwa urahisi.',
      'vi': 'Tải lên một bức ảnh để chúng tôi dễ dàng xác định bạn.',
      'zh_Hans': '上传照片以便我们轻松识别您。',
    },
    'p9lgrocc': {
      'en': 'Your Name',
      'ar': 'اسمك',
      'es': 'Su nombre',
      'fr': 'votre nom',
      'hi': 'तुम्हारा  नाम',
      'ru': 'Твое имя',
      'sw': 'Jina lako',
      'vi': 'Tên của bạn',
      'zh_Hans': '你的名字',
    },
    'ix96b0pv': {
      'en': 'Please enter a valid number...',
      'ar': 'من فضلك أدخل رقما صالحا...',
      'es': 'Por favor ingrese un número valido...',
      'fr': 'S&#39;il vous plait, entrez un nombre valide...',
      'hi': 'कृपया एक सही संख्या डालिये...',
      'ru': 'Пожалуйста введите правильное число...',
      'sw': 'Tafadhali weka nambari halali...',
      'vi': 'Vui lòng nhập một số hợp lệ...',
      'zh_Hans': '请输入一个有效的数字...',
    },
    'nhk2jca2': {
      'en': 'Your Age',
      'ar': 'عمرك',
      'es': 'Su edad',
      'fr': 'Votre âge',
      'hi': 'आपकी उम्र',
      'ru': 'Ваш возраст',
      'sw': 'Umri wako',
      'vi': 'Tuổi của bạn',
      'zh_Hans': '你的年龄',
    },
    '80qvp1g7': {
      'en': 'i.e. 34',
      'ar': 'أي 34',
      'es': 'es decir, 34',
      'fr': 'c&#39;est-à-dire 34',
      'hi': 'यानी 34',
      'ru': 'т.е. 34',
      'sw': 'yaani 34',
      'vi': 'tức là 34',
      'zh_Hans': '即 34',
    },
    '4ed9qtme': {
      'en': 'Ailments',
      'ar': 'الأمراض',
      'es': 'dolencias',
      'fr': 'Maux',
      'hi': 'रोगों',
      'ru': 'Болезни',
      'sw': 'Maradhi',
      'vi': 'Bệnh tật',
      'zh_Hans': '疾病',
    },
    'j6eqfifn': {
      'en': 'What types of allergies do you have..',
      'ar': 'ما أنواع الحساسية التي تعاني منها ..',
      'es': '¿Qué tipos de alergias tienes?',
      'fr': 'Quels types d&#39;allergies avez-vous..',
      'hi': 'आपको किस तरह की एलर्जी है..',
      'ru': 'Какие виды аллергии у вас есть..',
      'sw': 'Je, una allergy za aina gani..',
      'vi': 'Bạn bị những loại dị ứng nào ..',
      'zh_Hans': '你有什么类型的过敏..',
    },
    'thmp1id1': {
      'en': 'Your Birth Sex',
      'ar': 'الجنس عند الولادة',
      'es': 'Tu sexo de nacimiento',
      'fr': 'Votre sexe de naissance',
      'hi': 'आपका जन्म लिंग',
      'ru': 'Ваш секс при рождении',
      'sw': 'Jinsia yako ya Kuzaliwa',
      'vi': 'Giới tính khi sinh của bạn',
      'zh_Hans': '你的出生性别',
    },
    'yqes4yns': {
      'en': 'Male',
      'ar': 'ذكر',
      'es': 'Masculino',
      'fr': 'Homme',
      'hi': 'नर',
      'ru': 'Мужской',
      'sw': 'Mwanaume',
      'vi': 'Nam giới',
      'zh_Hans': '男性',
    },
    'yu9b4j1m': {
      'en': 'Female',
      'ar': 'أنثى',
      'es': 'Femenino',
      'fr': 'Femelle',
      'hi': 'महिला',
      'ru': 'женский',
      'sw': 'Mwanamke',
      'vi': 'Giống cái',
      'zh_Hans': '女性',
    },
    '3e8hk3ip': {
      'en': 'Undisclosed',
      'ar': 'غير معلنة',
      'es': 'no revelado',
      'fr': 'non dévoilé',
      'hi': 'अप्रकाशित',
      'ru': 'Нераскрыто',
      'sw': 'Haijafichuliwa',
      'vi': 'Không tiết lộ',
      'zh_Hans': '未公开',
    },
    'gxysqe2s': {
      'en': 'Add Another Profile',
      'ar': 'إضافة ملف تعريف آخر',
      'es': 'Agregar otro perfil',
      'fr': 'Ajouter un autre profil',
      'hi': 'एक और प्रोफ़ाइल जोड़ें',
      'ru': 'Добавить еще один профиль',
      'sw': 'Ongeza Wasifu Mwingine',
      'vi': 'Thêm hồ sơ khác',
      'zh_Hans': '添加另一个配置文件',
    },
    'aere2zkf': {
      'en': 'Complete Profile',
      'ar': 'الملف الشخصي الكامل',
      'es': 'Perfil completo',
      'fr': 'Profil complet',
      'hi': 'पूरा प्रोफाइल',
      'ru': 'Полный профиль',
      'sw': 'Kamilisha Wasifu',
      'vi': 'Hoàn thành hồ sơ',
      'zh_Hans': '完整档案',
    },
    'wlp3kg75': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // addAnotherProfile
  {
    'yk56quci': {
      'en': 'Add Another Profile',
      'ar': 'إضافة ملف تعريف آخر',
      'es': 'Agregar otro perfil',
      'fr': 'Ajouter un autre profil',
      'hi': 'एक और प्रोफ़ाइल जोड़ें',
      'ru': 'Добавить еще один профиль',
      'sw': 'Ongeza Wasifu Mwingine',
      'vi': 'Thêm hồ sơ khác',
      'zh_Hans': '添加另一个配置文件',
    },
    '4pycc3oq': {
      'en': 'Upload a photo for us to easily identify this person.',
      'ar': 'قم بتحميل صورة لنا للتعرف بسهولة على هذا الشخص.',
      'es':
          'Sube una foto para que podamos identificar fácilmente a esta persona.',
      'fr':
          'Téléchargez une photo pour que nous puissions identifier facilement cette personne.',
      'hi':
          'इस व्यक्ति को आसानी से पहचानने के लिए हमारे लिए एक फोटो अपलोड करें।',
      'ru':
          'Загрузите фотографию, чтобы мы могли легко идентифицировать этого человека.',
      'sw': 'Pakia picha ili tumtambue mtu huyu kwa urahisi.',
      'vi': 'Tải lên một bức ảnh để chúng tôi dễ dàng xác định người này.',
      'zh_Hans': '上传照片以便我们轻松识别此人。',
    },
    'watvxm5a': {
      'en': 'Persons Name',
      'ar': 'اسم الشخص',
      'es': 'Nombre de persona',
      'fr': 'Nom de la personne',
      'hi': 'व्यक्ति का नाम',
      'ru': 'Имя человека',
      'sw': 'Jina la Watu',
      'vi': 'Tên của người đó',
      'zh_Hans': '人名',
    },
    'fkyzt23t': {
      'en': 'Official name here...',
      'ar': 'الاسم الرسمي هنا ...',
      'es': 'Nombre oficial aquí...',
      'fr': 'Nom officiel ici...',
      'hi': 'यहां आधिकारिक नाम...',
      'ru': 'Официальное название здесь...',
      'sw': 'Jina rasmi hapa...',
      'vi': 'Tên chính thức ở đây ...',
      'zh_Hans': '正式名称在这里...',
    },
    '6nnc3ir2': {
      'en': 'Persons Age',
      'ar': 'عمر الأشخاص',
      'es': 'Edad de las personas',
      'fr': 'Âge des personnes',
      'hi': 'व्यक्तियों की आयु',
      'ru': 'Возраст лиц',
      'sw': 'Watu Umri',
      'vi': 'Tuổi người',
      'zh_Hans': '人年龄',
    },
    'uro1goau': {
      'en': 'i.e. 34',
      'ar': 'أي 34',
      'es': 'es decir, 34',
      'fr': 'c&#39;est-à-dire 34',
      'hi': 'यानी 34',
      'ru': 'т.е. 34',
      'sw': 'yaani 34',
      'vi': 'tức là 34',
      'zh_Hans': '即 34',
    },
    'sdmxprej': {
      'en': 'Persons Ailments',
      'ar': 'أمراض الأشخاص',
      'es': 'Dolencias de las personas',
      'fr': 'Maladies des personnes',
      'hi': 'व्यक्तियों की बीमारियां',
      'ru': 'Болезни людей',
      'sw': 'Magonjwa ya Watu',
      'vi': 'Người bệnh',
      'zh_Hans': '人的疾病',
    },
    'vwcg3hg7': {
      'en': 'What types of allergies do they have..',
      'ar': 'ما هي أنواع الحساسية التي يعانون منها ..',
      'es': 'Que tipos de alergias tienen..',
      'fr': 'Quels types d&#39;allergies ont-ils..',
      'hi': 'उन्हें किस तरह की एलर्जी है..',
      'ru': 'Какие виды аллергии бывают..',
      'sw': 'Je, wana allergy za aina gani..',
      'vi': 'Họ bị những loại dị ứng nào ..',
      'zh_Hans': '他们有什么类型的过敏..',
    },
    'xhiq0uxx': {
      'en': 'Location',
      'ar': 'موقع',
      'es': 'Localización',
      'fr': 'Emplacement',
      'hi': 'जगह',
      'ru': 'Место нахождения',
      'sw': 'Mahali',
      'vi': 'Địa điểm',
      'zh_Hans': '地点',
    },
    'n7hmjkuh': {
      'en': 'Please enter a valid email...',
      'ar': 'يرجى إدخال البريد الإلكتروني الصحيح...',
      'es':
          'Por favor introduzca una dirección de correo electrónico válida...',
      'fr': 'Veuillez entrer un email valide...',
      'hi': 'कृपया एक मान्य ईमेल पता प्रवेश करें...',
      'ru': 'Пожалуйста, введите действительный адрес электронной почты...',
      'sw': 'Tafadhali weka barua pepe halali...',
      'vi': 'Vui lòng nhập email hợp lệ...',
      'zh_Hans': '请输入有效电子邮件...',
    },
    'cer2zyib': {
      'en': 'Persons Birth Sex',
      'ar': 'الجنس عند الميلاد',
      'es': 'Personas Nacimiento Sexo',
      'fr': 'Personnes Naissance Sexe',
      'hi': 'व्यक्ति जन्म लिंग',
      'ru': 'Секс при рождении',
      'sw': 'Jinsia ya Kuzaliwa kwa Watu',
      'vi': 'Giới tính khi sinh của người',
      'zh_Hans': '出生性别',
    },
    'a2gtkx7c': {
      'en': 'Male',
      'ar': 'ذكر',
      'es': 'Masculino',
      'fr': 'Homme',
      'hi': 'नर',
      'ru': 'Мужской',
      'sw': 'Mwanaume',
      'vi': 'Nam giới',
      'zh_Hans': '男性',
    },
    'ofl06pbm': {
      'en': 'Female',
      'ar': 'أنثى',
      'es': 'Femenino',
      'fr': 'Femelle',
      'hi': 'महिला',
      'ru': 'женский',
      'sw': 'Mwanamke',
      'vi': 'Giống cái',
      'zh_Hans': '女性',
    },
    'b0rlmz12': {
      'en': 'Undisclosed',
      'ar': 'غير معلنة',
      'es': 'no revelado',
      'fr': 'non dévoilé',
      'hi': 'अप्रकाशित',
      'ru': 'Нераскрыто',
      'sw': 'Haijafichuliwa',
      'vi': 'Không tiết lộ',
      'zh_Hans': '未公开',
    },
    '6st3hn1g': {
      'en': 'Complete Profile',
      'ar': 'الملف الشخصي الكامل',
      'es': 'Perfil completo',
      'fr': 'Profil complet',
      'hi': 'पूरा प्रोफाइल',
      'ru': 'Полный профиль',
      'sw': 'Kamilisha Wasifu',
      'vi': 'Hoàn thành hồ sơ',
      'zh_Hans': '完整档案',
    },
    'gu5huzua': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // homePage
  {
    'gr6palpw': {
      'en': 'Good Morning',
      'ar': 'صباح الخير',
      'es': 'Buenos días',
      'fr': 'bon Matin',
      'hi': 'शुभ प्रभात',
      'ru': 'Доброе утро',
      'sw': 'Habari za asubuhi',
      'vi': 'Chào buổi sáng',
      'zh_Hans': '早上好',
    },
    'j4kcpl2g': {
      'en': 'Your next appointment',
      'ar': 'موعدك القادم',
      'es': 'Tu próxima cita',
      'fr': 'Votre prochain rendez-vous',
      'hi': 'आपकी अगली नियुक्ति',
      'ru': 'Ваша следующая встреча',
      'sw': 'Miadi yako ijayo',
      'vi': 'Cuộc hẹn tiếp theo của bạn',
      'zh_Hans': '您的下一次约会',
    },
    'hr5314j2': {
      'en': 'Rate Clinic',
      'ar': 'معدل العيادة',
      'es': 'Tarifa Clínica',
      'fr': 'Taux Clinique',
      'hi': 'रेट क्लिनिक',
      'ru': 'Оцените клинику',
      'sw': 'Kliniki ya kiwango',
      'vi': 'Đánh giá phòng khám',
      'zh_Hans': '率诊所',
    },
    'sjhuop5i': {
      'en': 'Book Appointment',
      'ar': 'موعد الكتاب',
      'es': 'Reservar una cita',
      'fr': 'Prendre rendez-vous',
      'hi': 'निर्धारित तारीख बुक करना',
      'ru': 'Записаться на прием',
      'sw': 'Uteuzi wa Kitabu',
      'vi': 'Đặt lịch hẹn',
      'zh_Hans': '预约',
    },
    'gzqhrr0s': {
      'en':
          'Schedule an appointment with a licensed professional within your location',
      'ar': 'حدد موعدًا مع متخصص مرخص في موقعك',
      'es':
          'Programe una cita con un profesional con licencia dentro de su ubicación',
      'fr': 'Prenez rendez-vous avec un professionnel agréé près de chez vous',
      'hi':
          'अपने स्थान के भीतर एक लाइसेंस प्राप्त पेशेवर के साथ अपॉइंटमेंट शेड्यूल करें',
      'ru': 'Назначьте встречу с лицензированным специалистом в вашем регионе',
      'sw': 'Panga miadi na mtaalamu aliyeidhinishwa ndani ya eneo lako',
      'vi':
          'Lên lịch một cuộc hẹn với một chuyên gia được cấp phép ở địa điểm của bạn',
      'zh_Hans': '安排与您所在位置的持牌专业人员的约会',
    },
    'erarifyw': {
      'en': 'Call the Helpline',
      'ar': 'اتصل بخط المساعدة',
      'es': 'Llame a la línea de ayuda',
      'fr': 'Appelez la ligne d&#39;assistance',
      'hi': 'हेल्पलाइन पर कॉल करें',
      'ru': 'Позвоните в службу поддержки',
      'sw': 'Piga Simu ya Msaada',
      'vi': 'Gọi cho Đường dây trợ giúp',
      'zh_Hans': '拨打帮助热线',
    },
    'h99lkewj': {
      'en': 'Give us a call for an intermediary translator if you need help ',
      'ar': 'اتصل بنا للحصول على مترجم وسيط إذا كنت بحاجة إلى مساعدة',
      'es': 'Llámenos para un traductor intermediario si necesita ayuda',
      'fr':
          'Appelez-nous pour un traducteur intermédiaire si vous avez besoin d&#39;aide',
      'hi':
          'यदि आपको सहायता की आवश्यकता हो तो हमें एक मध्यस्थ अनुवादक के लिए कॉल करें',
      'ru': 'Позвоните нам для переводчика-посредника, если вам нужна помощь',
      'sw': 'Tupigie simu mtafsiri mpatanishi ikiwa unahitaji usaidizi',
      'vi':
          'Hãy gọi cho chúng tôi để tìm một dịch giả trung gian nếu bạn cần trợ giúp',
      'zh_Hans': '如果您需要帮助，请致电我们寻求中介翻译',
    },
    'uepqn1no': {
      'en': 'Email Us',
      'ar': 'ارسل لنا عبر البريد الإلكتروني',
      'es': 'Envíenos un correo electrónico',
      'fr': 'Envoyez-nous un email',
      'hi': 'हमे ईमेल करे',
      'ru': 'Свяжитесь с нами по электронной почте',
      'sw': 'Tutumie Barua Pepe',
      'vi': 'Gửi email cho chúng tôi',
      'zh_Hans': '给我们发电子邮件',
    },
    'xb2bsrn2': {
      'en': 'Send us an email and we will get back to you within 2 days.',
      'ar': 'أرسل لنا بريدًا إلكترونيًا وسنعاود الاتصال بك في غضون يومين.',
      'es':
          'Envíenos un correo electrónico y nos pondremos en contacto con usted dentro de 2 días.',
      'fr': 'Envoyez-nous un e-mail et nous vous répondrons dans les 2 jours.',
      'hi': 'हमें एक ईमेल भेजें और हम 2 दिनों के भीतर आपसे संपर्क करेंगे।',
      'ru':
          'Отправьте нам электронное письмо, и мы свяжемся с вами в течение 2 дней.',
      'sw': 'Tutumie barua pepe na tutakujibu ndani ya siku 2.',
      'vi':
          'Gửi email cho chúng tôi và chúng tôi sẽ liên hệ lại với bạn trong vòng 2 ngày.',
      'zh_Hans': '给我们发送电子邮件，我们将在 2 天内回复您。',
    },
    '8l1krye2': {
      'en': 'About Us',
      'ar': 'معلومات عنا',
      'es': 'Sobre nosotros',
      'fr': 'À propos de nous',
      'hi': 'हमारे बारे में',
      'ru': 'О нас',
      'sw': 'Kuhusu sisi',
      'vi': 'Về chúng tôi',
      'zh_Hans': '关于我们',
    },
    '7s90b77g': {
      'en': ' Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // about_us
  {
    '2wh027o2': {
      'en': 'Goal:',
      'ar': 'هدف:',
      'es': 'Meta:',
      'fr': 'But:',
      'hi': 'लक्ष्य:',
      'ru': 'Цель:',
      'sw': 'Lengo:',
      'vi': 'Ghi bàn:',
      'zh_Hans': '目标：',
    },
    'o43jo65k': {
      'en':
          'Ensure seeks to connect uninsured communities and non-native speakers to medical resources (free clinics, community health care centers) through an app that provides hours/dates of operation, the demographic profile of patients, internal/external services offered within Texas counties.\n',
      'ar':
          'ضمان يسعى إلى ربط المجتمعات غير المؤمنة والمتحدثين غير الأصليين بالموارد الطبية (العيادات المجانية ، ومراكز الرعاية الصحية المجتمعية) من خلال تطبيق يوفر ساعات / تواريخ التشغيل ، والملف الديموغرافي للمرضى ، والخدمات الداخلية / الخارجية المقدمة ، والمسافة النسبية إلى عيادات داخل مقاطعات تكساس.',
      'es':
          'Garantizar busca conectar comunidades sin seguro y hablantes no nativos con recursos médicos (clínicas gratuitas, centros de atención médica comunitaria) a través de una aplicación que brinda horas/fechas de operación, el perfil demográfico de los pacientes, servicios internos/externos ofrecidos y la distancia relativa a clínicas dentro de los condados de Texas.',
      'fr':
          'Assurer cherche à connecter les communautés non assurées et les locuteurs non natifs aux ressources médicales (cliniques gratuites, centres de soins de santé communautaires) via une application qui fournit les heures/dates d&#39;ouverture, le profil démographique des patients, les services internes/externes offerts et la distance relative aux cliniques dans les comtés du Texas.',
      'hi':
          'सुनिश्चित करें कि एक ऐप के माध्यम से गैर-बीमित समुदायों और गैर-देशी वक्ताओं को चिकित्सा संसाधनों (मुफ्त क्लीनिक, सामुदायिक स्वास्थ्य देखभाल केंद्र) से जोड़ना चाहता है जो ऑपरेशन के घंटे / तारीखें, रोगियों की जनसांख्यिकीय प्रोफ़ाइल, आंतरिक / बाहरी सेवाओं की पेशकश, और सापेक्ष दूरी प्रदान करता है। टेक्सास काउंटियों के भीतर क्लीनिकों के लिए।',
      'ru':
          'Обеспечить подключение незастрахованных сообществ и лиц, не являющихся носителями языка, к медицинским ресурсам (бесплатным клиникам, общественным центрам здравоохранения) через приложение, которое предоставляет часы/даты работы, демографический профиль пациентов, предлагаемые внутренние/внешние услуги и относительное расстояние в клиники в округах Техаса.',
      'sw':
          'Hakikisha inalenga kuunganisha jumuiya zisizo na bima na wazungumzaji wasio wazawa kwenye rasilimali za matibabu (zahanati zisizolipishwa, vituo vya afya vya jamii) kupitia programu ambayo hutoa saa/tarehe za operesheni, wasifu wa idadi ya wagonjwa, huduma za ndani/nje zinazotolewa na umbali fulani. kwa kliniki ndani ya kaunti za Texas.',
      'vi':
          'Đảm bảo tìm cách kết nối các cộng đồng không có bảo hiểm và người không phải là người bản ngữ với các nguồn y tế (phòng khám miễn phí, trung tâm chăm sóc sức khỏe cộng đồng) thông qua một ứng dụng cung cấp giờ / ngày hoạt động, hồ sơ nhân khẩu học của bệnh nhân, các dịch vụ nội bộ / bên ngoài được cung cấp và khoảng cách tương đối đến các phòng khám trong các quận của Texas.',
      'zh_Hans':
          'Ensure 旨在通过提供营业时间/日期、患者人口统计资料、提供的内部/外部服务以及相对距离的应用程序将未投保社区和非母语人士与医疗资源（免费诊所、社区保健中心）联系起来到德克萨斯州县内的诊所。',
    },
    'xsgphhkz': {
      'en':
          'Among states, Texas ranked second in its number of persons recently uninsured (659,000) in need of healthcare. Uninsured rate of those without health insurance coverage in Texas is 18.4%. With the Ensure App we will connect those communities to free clinic sources.\n',
      'ar':
          'بين الولايات ، احتلت ولاية تكساس المرتبة الثانية من حيث عدد الأشخاص غير المؤمن عليهم مؤخرًا (659000) ممن يحتاجون إلى رعاية صحية. معدل غير المؤمن عليهم لمن ليس لديهم تغطية تأمين صحي في تكساس هو 18.4٪. باستخدام تطبيق &quot;ضمان&quot; ، سنربط هذه المجتمعات بمصادر العيادة المجانية.',
      'es':
          'Entre los estados, Texas ocupó el segundo lugar en el número de personas recientemente sin seguro (659,000) que necesitan atención médica. La tasa de personas sin seguro médico sin cobertura de seguro médico en Texas es del 18,4 %. Con la aplicación Guarantee, conectaremos esas comunidades con fuentes clínicas gratuitas.',
      'fr':
          'Parmi les États, le Texas s&#39;est classé deuxième pour le nombre de personnes récemment non assurées (659 000) ayant besoin de soins de santé. Le taux de personnes non assurées sans couverture d&#39;assurance maladie au Texas est de 18,4 %. Avec l&#39;application Ensure, nous connecterons ces communautés à des sources de cliniques gratuites.',
      'hi':
          'राज्यों के बीच, टेक्सास स्वास्थ्य देखभाल की जरूरत में हाल ही में अपूर्वदृष्ट (659,000) व्यक्तियों की संख्या में दूसरे स्थान पर है। टेक्सास में स्वास्थ्य बीमा कवरेज के बिना बीमाकृत दर 18.4% है। सुनिश्चित ऐप के साथ हम उन समुदायों को मुफ्त क्लिनिक स्रोतों से जोड़ेंगे।',
      'ru':
          'Среди штатов Техас занимает второе место по количеству недавно незастрахованных лиц (659 000 человек), нуждающихся в медицинской помощи. Уровень незастрахованных лиц без медицинской страховки в Техасе составляет 18,4%. С помощью приложения Sure мы свяжем эти сообщества с бесплатными источниками для клиник.',
      'sw':
          'Miongoni mwa majimbo, Texas ilishika nafasi ya pili kwa idadi yake ya watu wasio na bima hivi karibuni (659,000) wanaohitaji huduma ya afya. Kiwango kisicho na bima cha wale wasio na bima ya afya huko Texas ni 18.4%. Kwa Programu ya Hakikisha tutaunganisha jumuiya hizo kwenye vyanzo vya kliniki bila malipo.',
      'vi':
          'Trong số các tiểu bang, Texas đứng thứ hai về số người gần đây không có bảo hiểm (659.000 người) cần được chăm sóc sức khỏe. Tỷ lệ không có bảo hiểm của những người không có bảo hiểm y tế ở Texas là 18,4%. Với Ứng dụng Đảm bảo, chúng tôi sẽ kết nối những cộng đồng đó với các nguồn phòng khám miễn phí.',
      'zh_Hans':
          '在各州中，德克萨斯州在最近没有保险的人数（659,000 人）中排名第二，需要医疗保健。德克萨斯州没有医疗保险的人的未投保率为 18.4%。通过 Ensure 应用程序，我们将这些社区与免费诊所资源联系起来。',
    },
    'mm2jvs7l': {
      'en': 'Nirvana M',
      'ar': 'نيرفانا م',
      'es': 'nirvana m',
      'fr': 'Nirvâna M',
      'hi': 'निर्वाण एम',
      'ru': 'Нирвана М',
      'sw': 'Nirvana M',
      'vi': 'Nirvana M',
      'zh_Hans': '涅槃',
    },
    'scybqp3r': {
      'en': 'Aileen L',
      'ar': 'أيلين إل',
      'es': 'aileen l',
      'fr': 'Aileen L',
      'hi': 'ऐलीन ली',
      'ru': 'Эйлин Л',
      'sw': 'Aileen L',
      'vi': 'Aileen L',
      'zh_Hans': '艾琳大号',
    },
    'byxi749s': {
      'en': 'About Ensure',
      'ar': 'حول ضمان',
      'es': 'Acerca de Garantizar',
      'fr': 'À propos d&#39;Ensure',
      'hi': 'सुनिश्चित के बारे में',
      'ru': 'Об обеспечении',
      'sw': 'Kuhusu Hakikisha',
      'vi': 'Giới thiệu về Đảm bảo',
      'zh_Hans': '关于确保',
    },
  },
  // myAppointments
  {
    '2lm771b2': {
      'en': 'Appointments',
      'ar': 'تعيينات',
      'es': 'Equipo',
      'fr': 'Rendez-vous',
      'hi': 'नियुक्ति',
      'ru': 'Назначения',
      'sw': 'Miadi',
      'vi': 'Các cuộc hẹn',
      'zh_Hans': '约会',
    },
    'h0dhhlj4': {
      'en': 'My Appointments',
      'ar': 'المواعيد الخاصة بي',
      'es': 'Mis citas',
      'fr': 'Mes rendez-vous',
      'hi': 'मेरी नियुक्तियाँ',
      'ru': 'Мои встречи',
      'sw': 'Miadi Yangu',
      'vi': 'Cuộc hẹn của tôi',
      'zh_Hans': '我的约会',
    },
    '07vy0jcg': {
      'en': 'For',
      'ar': 'ل',
      'es': 'Para',
      'fr': 'Pour',
      'hi': 'के लिए',
      'ru': 'За',
      'sw': 'Kwa',
      'vi': 'Vì',
      'zh_Hans': '为了',
    },
    't8wowhk6': {
      'en': 'Appointments',
      'ar': 'تعيينات',
      'es': 'Equipo',
      'fr': 'Rendez-vous',
      'hi': 'नियुक्ति',
      'ru': 'Назначения',
      'sw': 'Miadi',
      'vi': 'Các cuộc hẹn',
      'zh_Hans': '约会',
    },
  },
  // profilePage
  {
    'tbsmwtof': {
      'en': 'Ailments',
      'ar': 'الأمراض',
      'es': 'dolencias',
      'fr': 'Maux',
      'hi': 'रोगों',
      'ru': 'Болезни',
      'sw': 'Maradhi',
      'vi': 'Bệnh tật',
      'zh_Hans': '疾病',
    },
    'q7c94avp': {
      'en': 'Next Appointment',
      'ar': 'الموعد التالي',
      'es': 'Próxima cita',
      'fr': 'Prochain rendez-vous',
      'hi': 'अगली नियुक्ति',
      'ru': 'Следующая встреча',
      'sw': 'Uteuzi Ujao',
      'vi': 'Cuộc hẹn tiếp theo',
      'zh_Hans': '下次预约',
    },
    'fkoyug8e': {
      'en': 'Aug 20, 2021',
      'ar': '20 أغسطس 2021',
      'es': '20 de agosto de 2021',
      'fr': '20 août 2021',
      'hi': 'अगस्त 20, 2021',
      'ru': '20 авг. 2021 г.',
      'sw': 'Agosti 20, 2021',
      'vi': '20 tháng 8, 2021',
      'zh_Hans': '2021 年 8 月 20 日',
    },
    'v7gtwr69': {
      'en': 'Past Appointments',
      'ar': 'المواعيد السابقة',
      'es': 'Citas pasadas',
      'fr': 'Rendez-vous passés',
      'hi': 'पिछली नियुक्तियां',
      'ru': 'Прошлые встречи',
      'sw': 'Uteuzi Uliopita',
      'vi': 'Các cuộc hẹn trong quá khứ',
      'zh_Hans': '过去的约会',
    },
    'pky58zmx': {
      'en': '[Appointment Type]',
      'ar': '[نوع الموعد]',
      'es': '[Tipo de cita]',
      'fr': '[Type de rendez-vous]',
      'hi': '[नियुक्ति प्रकार]',
      'ru': '[Тип встречи]',
      'sw': '[Aina ya Uteuzi]',
      'vi': '[Loại cuộc hẹn]',
      'zh_Hans': '【预约类型】',
    },
    'ab136zgy': {
      'en': '[date_time]',
      'ar': '[تاريخ_وقت]',
      'es': '[fecha y hora]',
      'fr': '[date_heure]',
      'hi': '[दिनांक और समय]',
      'ru': '[дата_время]',
      'sw': '[date_time]',
      'vi': '[ngày giờ]',
      'zh_Hans': '[约会时间]',
    },
    'et10iqhx': {
      'en': 'For',
      'ar': 'ل',
      'es': 'Para',
      'fr': 'Pour',
      'hi': 'के लिए',
      'ru': 'За',
      'sw': 'Kwa',
      'vi': 'Vì',
      'zh_Hans': '为了',
    },
    'fitbku00': {
      'en': '[display_name]',
      'ar': '[اسم العرض]',
      'es': '[nombre para mostrar]',
      'fr': '[Afficher un nom]',
      'hi': '[प्रदर्शित होने वाला नाम]',
      'ru': '[отображаемое имя]',
      'sw': '[onyesha_jina]',
      'vi': '[tên hiển thị]',
      'zh_Hans': '[显示名称]',
    },
    'g28tgoeo': {
      'en': 'Profile',
      'ar': 'حساب تعريفي',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ru': 'Профиль',
      'sw': 'Wasifu',
      'vi': 'Hồ sơ',
      'zh_Hans': '轮廓',
    },
  },
  // appointmentDetails
  {
    'mw7ce7di': {
      'en': 'Details',
      'ar': 'تفاصيل',
      'es': 'Detalles',
      'fr': 'Des détails',
      'hi': 'विवरण',
      'ru': 'Подробности',
      'sw': 'Maelezo',
      'vi': 'Thông tin chi tiết',
      'zh_Hans': '细节',
    },
    'f61imjwl': {
      'en': 'Type of Appointment',
      'ar': 'نوع التعيين',
      'es': 'Tipo de cita',
      'fr': 'Type de rendez-vous',
      'hi': 'नियुक्ति का प्रकार',
      'ru': 'Тип назначения',
      'sw': 'Aina ya Uteuzi',
      'vi': 'Loại cuộc hẹn',
      'zh_Hans': '约会类型',
    },
    'd4cs51dd': {
      'en': 'What’s the problem?',
      'ar': 'ما هي المشكلة؟',
      'es': '¿Cuál es el problema?',
      'fr': 'Quel est le problème?',
      'hi': 'समस्या क्या है?',
      'ru': 'В чем проблема?',
      'sw': 'Tatizo ni nini?',
      'vi': 'Vấn đề là gì?',
      'zh_Hans': '有什么问题？',
    },
    '76l9kud5': {
      'en': 'For',
      'ar': 'ل',
      'es': 'Para',
      'fr': 'Pour',
      'hi': 'के लिए',
      'ru': 'За',
      'sw': 'Kwa',
      'vi': 'Vì',
      'zh_Hans': '为了',
    },
    'wj1246to': {
      'en': 'When',
      'ar': 'متى',
      'es': 'Cuando',
      'fr': 'Lorsque',
      'hi': 'कब',
      'ru': 'Когда',
      'sw': 'Lini',
      'vi': 'Khi nào',
      'zh_Hans': '什么时候',
    },
    'r01ugxk9': {
      'en': 'Reschedule',
      'ar': 'إعادة الجدولة',
      'es': 'Reprogramar',
      'fr': 'Reprogrammer',
      'hi': 'पुनर्निर्धारित',
      'ru': 'Перенести',
      'sw': 'Panga upya',
      'vi': 'Sắp xếp lại',
      'zh_Hans': '改期',
    },
    'a4a7odrp': {
      'en': 'Cancel Appointment',
      'ar': 'إلغاء التعيين',
      'es': 'Cancelar cita',
      'fr': 'Annuler rendez-vous',
      'hi': 'अपॉइंटमेंट रद्द करें',
      'ru': 'Отменить встречу',
      'sw': 'Ghairi Uteuzi',
      'vi': 'Hủy cuộc hẹn',
      'zh_Hans': '取消预约',
    },
    'u1wtoy2w': {
      'en': 'Home Page',
      'ar': 'الصفحة الرئيسية',
      'es': 'Página de inicio',
      'fr': 'Page d&#39;accueil',
      'hi': 'होम पेज',
      'ru': 'Домашняя страница',
      'sw': 'Ukurasa wa Nyumbani',
      'vi': 'Trang chủ',
      'zh_Hans': '主页',
    },
    'q1ch0hc3': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // editProfile
  {
    '8i7v5wgo': {
      'en': 'Edit Profile',
      'ar': 'تعديل الملف الشخصي',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ru': 'Редактировать профиль',
      'sw': 'Hariri Wasifu',
      'vi': 'Chỉnh sửa hồ sơ',
      'zh_Hans': '编辑个人资料',
    },
    'nmxefu6t': {
      'en': 'Change Photo',
      'ar': 'غير الصوره',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'hi': 'तस्वीर बदलिये',
      'ru': 'Измени фотографию',
      'sw': 'BADILISHA picha',
      'vi': 'Thay đổi hình ảnh',
      'zh_Hans': '更改照片',
    },
    'o1li69mt': {
      'en': 'Your Name',
      'ar': 'اسمك',
      'es': 'Su nombre',
      'fr': 'votre nom',
      'hi': 'तुम्हारा  नाम',
      'ru': 'Твое имя',
      'sw': 'Jina lako',
      'vi': 'Tên của bạn',
      'zh_Hans': '你的名字',
    },
    'a6pszme0': {
      'en': 'Please enter a valid number...',
      'ar': 'من فضلك أدخل رقما صالحا...',
      'es': 'Por favor ingrese un número valido...',
      'fr': 'S&#39;il vous plait, entrez un nombre valide...',
      'hi': 'कृपया एक सही संख्या डालिये...',
      'ru': 'Пожалуйста введите правильное число...',
      'sw': 'Tafadhali weka nambari halali...',
      'vi': 'Vui lòng nhập một số hợp lệ...',
      'zh_Hans': '请输入一个有效的数字...',
    },
    'hrxi3tlj': {
      'en': 'Email Address',
      'ar': 'عنوان بريد الكتروني',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ru': 'Адрес электронной почты',
      'sw': 'Barua pepe',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    '8dpg51l3': {
      'en': 'Your email',
      'ar': 'بريدك الالكتروني',
      'es': 'Tu correo electrónico',
      'fr': 'Votre e-mail',
      'hi': 'तुम्हारा ईमेल',
      'ru': 'Ваш адрес электронной почты',
      'sw': 'Barua pepe yako',
      'vi': 'Email của bạn',
      'zh_Hans': '你的邮件',
    },
    'd6t5qnrm': {
      'en': 'Your Age',
      'ar': 'عمرك',
      'es': 'Su edad',
      'fr': 'Votre âge',
      'hi': 'आपकी उम्र',
      'ru': 'Ваш возраст',
      'sw': 'Umri wako',
      'vi': 'Tuổi của bạn',
      'zh_Hans': '你的年龄',
    },
    'imn1hog5': {
      'en': 'i.e. 34',
      'ar': 'أي 34',
      'es': 'es decir, 34',
      'fr': 'c&#39;est-à-dire 34',
      'hi': 'यानी 34',
      'ru': 'т.е. 34',
      'sw': 'yaani 34',
      'vi': 'tức là 34',
      'zh_Hans': '即 34',
    },
    'v6hpnveg': {
      'en': 'Ailments',
      'ar': 'الأمراض',
      'es': 'dolencias',
      'fr': 'Maux',
      'hi': 'रोगों',
      'ru': 'Болезни',
      'sw': 'Maradhi',
      'vi': 'Bệnh tật',
      'zh_Hans': '疾病',
    },
    'vgduv96m': {
      'en': 'What types of allergies do you have..',
      'ar': 'ما أنواع الحساسية التي تعاني منها ..',
      'es': '¿Qué tipos de alergias tienes?',
      'fr': 'Quels types d&#39;allergies avez-vous..',
      'hi': 'आपको किस तरह की एलर्जी है..',
      'ru': 'Какие виды аллергии у вас есть..',
      'sw': 'Je, una allergy za aina gani..',
      'vi': 'Bạn bị những loại dị ứng nào ..',
      'zh_Hans': '你有什么类型的过敏..',
    },
    '1vzf239j': {
      'en': 'Your Birth Sex',
      'ar': 'الجنس عند الولادة',
      'es': 'Tu sexo de nacimiento',
      'fr': 'Votre sexe de naissance',
      'hi': 'आपका जन्म लिंग',
      'ru': 'Ваш секс при рождении',
      'sw': 'Jinsia yako ya Kuzaliwa',
      'vi': 'Giới tính khi sinh của bạn',
      'zh_Hans': '你的出生性别',
    },
    '2uctuuyi': {
      'en': 'Male',
      'ar': 'ذكر',
      'es': 'Masculino',
      'fr': 'Homme',
      'hi': 'नर',
      'ru': 'Мужской',
      'sw': 'Mwanaume',
      'vi': 'Nam giới',
      'zh_Hans': '男性',
    },
    't7t6b95h': {
      'en': 'Female',
      'ar': 'أنثى',
      'es': 'Femenino',
      'fr': 'Femelle',
      'hi': 'महिला',
      'ru': 'женский',
      'sw': 'Mwanamke',
      'vi': 'Giống cái',
      'zh_Hans': '女性',
    },
    'z1y7kk7f': {
      'en': 'Undisclosed',
      'ar': 'غير معلنة',
      'es': 'no revelado',
      'fr': 'non dévoilé',
      'hi': 'अप्रकाशित',
      'ru': 'Нераскрыто',
      'sw': 'Haijafichuliwa',
      'vi': 'Không tiết lộ',
      'zh_Hans': '未公开',
    },
    'oayw4ikn': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ru': 'Сохранить изменения',
      'sw': 'Hifadhi mabadiliko',
      'vi': 'Lưu thay đổi',
      'zh_Hans': '保存更改',
    },
    'vgsn3dct': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // Settings
  {
    'r579s4v0': {
      'en':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'ar': 'اختر الإشعارات التي تريد تلقيها أدناه وسنقوم بتحديث الإعدادات.',
      'es':
          'Elija qué notificaciones desea recibir a continuación y actualizaremos la configuración.',
      'fr':
          'Choisissez les notifications que vous souhaitez recevoir ci-dessous et nous mettrons à jour les paramètres.',
      'hi':
          'चुनें कि आप नीचे कौन-सी सूचनाएं प्राप्त करना चाहते हैं और हम सेटिंग अपडेट कर देंगे।',
      'ru':
          'Выберите ниже, какие уведомления вы хотите получать, и мы обновим настройки.',
      'sw':
          'Chagua ni arifa zipi ungependa kupokea hapa chini na tutasasisha mipangilio.',
      'vi':
          'Chọn thông báo bạn muốn nhận bên dưới và chúng tôi sẽ cập nhật cài đặt.',
      'zh_Hans': '在下方选择您要接收的通知，我们将更新设置。',
    },
    'zm4iy3ht': {
      'en': 'Push Notifications',
      'ar': 'دفع الإخطارات',
      'es': 'Notificaciones push',
      'fr': 'Notifications push',
      'hi': 'सूचनाएं धक्का',
      'ru': 'Всплывающие уведомления',
      'sw': 'Arifa za Push',
      'vi': 'Đẩy thông báo',
      'zh_Hans': '推送通知',
    },
    '6up1edap': {
      'en': 'Receive Push notifications from our app',
      'ar': 'تلقي الإخطارات من التطبيق لدينا',
      'es': 'Recibe notificaciones Push desde nuestra app',
      'fr': 'Recevez des notifications Push de notre application',
      'hi': 'हमारे ऐप से पुश सूचनाएं प्राप्त करें',
      'ru': 'Получайте Push-уведомления от нашего приложения',
      'sw': 'Pokea arifa za Push kutoka kwa programu yetu',
      'vi': 'Nhận thông báo đẩy từ ứng dụng của chúng tôi',
      'zh_Hans': '从我们的应用程序接收推送通知',
    },
    'iwx6zb0w': {
      'en': 'Email Notifications',
      'ar': 'اشعارات البريد الالكتروني',
      'es': 'Notificaciónes de Correo Electrónico',
      'fr': 'Notifications par email',
      'hi': 'ईमेल सूचनाएं',
      'ru': 'Уведомления по электронной почте',
      'sw': 'Arifa za Barua Pepe',
      'vi': 'thông báo thư',
      'zh_Hans': '邮件通知',
    },
    '59u57pwc': {
      'en': 'Receive email notifications about new info.',
      'ar': 'تلقي إخطارات البريد الإلكتروني حول المعلومات الجديدة.',
      'es':
          'Reciba notificaciones por correo electrónico sobre nueva información.',
      'fr':
          'Recevez des notifications par e-mail sur les nouvelles informations.',
      'hi': 'नई जानकारी के बारे में ईमेल सूचनाएं प्राप्त करें।',
      'ru': 'Получайте уведомления по электронной почте о новой информации.',
      'sw': 'Pokea arifa za barua pepe kuhusu maelezo mapya.',
      'vi': 'Nhận thông báo qua email về thông tin mới.',
      'zh_Hans': '接收有关新信息的电子邮件通知。',
    },
    '6z73i06b': {
      'en': 'Location Services',
      'ar': 'خدمات الموقع',
      'es': 'Servicios de localización',
      'fr': 'Services de location',
      'hi': 'स्थान सेवाएं',
      'ru': 'Сервисы определения местоположения',
      'sw': 'Huduma za Mahali',
      'vi': 'Dịch vụ định vị',
      'zh_Hans': '位置服务',
    },
    '0b762nuy': {
      'en':
          'Allow us to track your location, this helps us find free healthcare services near you.',
      'ar':
          'اسمح لنا بتتبع موقعك ، فهذا يساعدنا في العثور على خدمات رعاية صحية مجانية بالقرب منك.',
      'es':
          'Permítanos rastrear su ubicación, esto nos ayuda a encontrar servicios de atención médica gratuitos cerca de usted.',
      'fr':
          'Permettez-nous de suivre votre position, cela nous aide à trouver des services de santé gratuits près de chez vous.',
      'hi':
          'हमें आपके स्थान को ट्रैक करने की अनुमति दें, इससे हमें आपके आस-पास निःशुल्क स्वास्थ्य सेवा खोजने में मदद मिलती है।',
      'ru':
          'Разрешите нам отслеживать ваше местоположение, это поможет нам найти бесплатные медицинские услуги рядом с вами.',
      'sw':
          'Ruhusu kufuatilia eneo lako, hii hutusaidia kupata huduma za afya bila malipo karibu nawe.',
      'vi':
          'Cho phép chúng tôi theo dõi vị trí của bạn, điều này giúp chúng tôi tìm thấy các dịch vụ chăm sóc sức khỏe miễn phí gần bạn.',
      'zh_Hans': '允许我们跟踪您的位置，这有助于我们找到您附近的免费医疗保健服务。',
    },
    'on8nb86b': {
      'en': 'Save  Changes',
      'ar': 'حفظ التغييرات',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ru': 'Сохранить изменения',
      'sw': 'Hifadhi mabadiliko',
      'vi': 'Lưu thay đổi',
      'zh_Hans': '保存更改',
    },
    'lg3r35z5': {
      'en': 'Settings',
      'ar': 'إعدادات',
      'es': 'Ajustes',
      'fr': 'Réglages',
      'hi': 'समायोजन',
      'ru': 'Настройки',
      'sw': 'Mipangilio',
      'vi': 'Cài đặt',
      'zh_Hans': '设置',
    },
  },
  // language3
  {
    'cpngrwg2': {
      'en': 'Language',
      'ar': 'لغة',
      'es': 'Idioma',
      'fr': 'Langue',
      'hi': 'भाषा',
      'ru': 'Язык',
      'sw': 'Lugha',
      'vi': 'Ngôn ngữ',
      'zh_Hans': '语言',
    },
    'mjcnvs4e': {
      'en': 'Purchase Books',
      'ar': 'شراء الكتب',
      'es': 'Compra de libros',
      'fr': 'Acheter des livres',
      'hi': 'पुस्तकें खरीदें',
      'ru': 'Купить книги',
      'sw': 'Nunua Vitabu',
      'vi': 'Mua sách',
      'zh_Hans': '购买书籍',
    },
    'sw1ldxks': {
      'en': 'Buy and view all your favorite books you find in this library.',
      'ar': 'اشترِ واعرض جميع كتبك المفضلة التي تجدها في هذه المكتبة.',
      'es':
          'Compre y vea todos sus libros favoritos que encuentre en esta biblioteca.',
      'fr':
          'Achetez et consultez tous vos livres préférés que vous trouvez dans cette bibliothèque.',
      'hi':
          'अपनी सभी पसंदीदा पुस्तकें खरीदें और देखें जो आपको इस पुस्तकालय में मिलती हैं।',
      'ru':
          'Купите и просмотрите все ваши любимые книги, которые вы найдете в этой библиотеке.',
      'sw':
          'Nunua na utazame vitabu vyako vyote unavyovipenda unavyopata katika maktaba hii.',
      'vi':
          'Mua và xem tất cả các cuốn sách yêu thích của bạn mà bạn tìm thấy trong thư viện này.',
      'zh_Hans': '购买并查看您在此图书馆中找到的所有您喜爱的书籍。',
    },
    'tvfhg5z5': {
      'en': 'Review Purchases',
      'ar': 'مراجعة المشتريات',
      'es': 'Revisar compras',
      'fr': 'Examiner les achats',
      'hi': 'खरीदारी की समीक्षा करें',
      'ru': 'Обзор покупок',
      'sw': 'Kagua Ununuzi',
      'vi': 'Xem lại các giao dịch mua',
      'zh_Hans': '审查购买',
    },
    'na5tc7hy': {
      'en':
          'Keep track of all your purchases that you have made, want to trade books in? Go ahead and list them for exchange.',
      'ar':
          'تتبع جميع مشترياتك التي قمت بها ، هل تريد تداول الكتب؟ المضي قدما وإدراجهم للتبادل.',
      'es':
          'Mantenga un registro de todas sus compras que ha realizado, ¿quiere intercambiar libros? Continúe y anótelos para el intercambio.',
      'fr':
          'Gardez une trace de tous vos achats que vous avez effectués, souhaitez-vous échanger des livres ? Allez-y et listez-les pour l&#39;échange.',
      'hi':
          'अपनी सभी खरीदारी पर नज़र रखें, जो आपने की हैं, पुस्तकों का व्यापार करना चाहते हैं? आगे बढ़ो और उन्हें विनिमय के लिए सूचीबद्ध करें।',
      'ru':
          'Следите за всеми своими покупками, которые вы сделали, хотите обменять книги? Идите вперед и перечислите их для обмена.',
      'sw':
          'Fuatilia ununuzi wako wote ambao umefanya, unataka kufanya biashara ya vitabu? Endelea na uziorodheshe kwa kubadilishana.',
      'vi':
          'Theo dõi tất cả các giao dịch mua của bạn mà bạn đã thực hiện, muốn đổi sách? Hãy tiếp tục và liệt kê chúng để trao đổi.',
      'zh_Hans': '跟踪您购买的所有商品，想要换购书籍吗？继续列出它们以进行交换。',
    },
    'p7hmr9xu': {
      'en': 'Save Change',
      'ar': 'حفظ التغيير',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'hi': 'बदलाव सुरक्षित करे',
      'ru': 'Сохранить изменения',
      'sw': 'Hifadhi Mabadiliko',
      'vi': 'Lưu thay đổi',
      'zh_Hans': '保存更改',
    },
  },
  // texascounties
  {
    '6hirh4el': {
      'en': 'Texas Counties',
      'ar': 'مقاطعات تكساس',
      'es': 'Condados de Texas',
      'fr': 'Comtés du Texas',
      'hi': 'टेक्सास काउंटी',
      'ru': 'Округа Техаса',
      'sw': 'Wilaya za Texas',
      'vi': 'Hạt Texas',
      'zh_Hans': '德克萨斯县',
    },
    'zup8jsuf': {
      'en': 'Select one of the Texas Counties below.',
      'ar': 'حدد إحدى مقاطعات تكساس أدناه.',
      'es': 'Seleccione uno de los condados de Texas a continuación.',
      'fr': 'Sélectionnez l&#39;un des comtés du Texas ci-dessous.',
      'hi': 'नीचे टेक्सास काउंटियों में से किसी एक का चयन करें।',
      'ru': 'Выберите один из округов Техаса ниже.',
      'sw': 'Chagua moja ya Kaunti za Texas hapa chini.',
      'vi': 'Chọn một trong các Quận Texas bên dưới.',
      'zh_Hans': '选择下面的德克萨斯县之一。',
    },
    '90cyn2qa': {
      'en': 'El Paso',
      'ar': 'الباسو',
      'es': 'El Paso',
      'fr': 'El Paso',
      'hi': 'एल पासो',
      'ru': 'Эль-Пасо',
      'sw': 'El Paso',
      'vi': 'El Paso',
      'zh_Hans': '埃尔帕索',
    },
    'yfq49va1': {
      'en': 'Harris ',
      'ar': 'هاريس',
      'es': 'harris',
      'fr': 'Harris',
      'hi': 'हैरिस',
      'ru': 'Харрис',
      'sw': 'Harris',
      'vi': 'Harris',
      'zh_Hans': '哈里斯',
    },
    'tx3xrtwp': {
      'en': 'Tarrant',
      'ar': 'تارانت',
      'es': 'Tarrant',
      'fr': 'Tarrant',
      'hi': 'टारेंट',
      'ru': 'Таррант',
      'sw': 'Tarrant',
      'vi': 'Tarrant',
      'zh_Hans': '塔兰特',
    },
    'cmyo35jl': {
      'en': 'Dallas',
      'ar': 'دالاس',
      'es': 'dallas',
      'fr': 'Dallas',
      'hi': 'डलास',
      'ru': 'Даллас',
      'sw': 'Dallas',
      'vi': 'Dallas',
      'zh_Hans': '达拉斯',
    },
    'ytu4yha3': {
      'en': 'Bexar',
      'ar': 'بيكسار',
      'es': 'Béxar',
      'fr': 'Bexar',
      'hi': 'बेक्सार',
      'ru': 'Бексар',
      'sw': 'Bexar',
      'vi': 'Bexar',
      'zh_Hans': '贝克萨',
    },
    '1dif0ppr': {
      'en': 'Travis',
      'ar': 'ترافيس',
      'es': 'Travis',
      'fr': 'Travis',
      'hi': 'ट्रैविस',
      'ru': 'Трэвис',
      'sw': 'Travis',
      'vi': 'Travis',
      'zh_Hans': '特拉维斯',
    },
    'ioyid666': {
      'en': 'Hidalgo',
      'ar': 'هيدالجو',
      'es': 'Hidalgo',
      'fr': 'Hidalgo',
      'hi': 'हिडलगो',
      'ru': 'Идальго',
      'sw': 'Hidalgo',
      'vi': 'Hidalgo',
      'zh_Hans': '伊达尔戈',
    },
    'psgiavgy': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // ElPaso
  {
    '0oew64wo': {
      'en': 'El Paso',
      'ar': 'الباسو',
      'es': 'El Paso',
      'fr': 'El Paso',
      'hi': 'एल पासो',
      'ru': 'Эль-Пасо',
      'sw': 'El Paso',
      'vi': 'El Paso',
      'zh_Hans': '埃尔帕索',
    },
    '9sc7vkkj': {
      'en': 'Pasadena Health Center:\n',
      'ar': 'مركز باسادينا الصحي:',
      'es': 'Centro de salud de Pasadena:',
      'fr': 'Centre de santé de Pasadena :',
      'hi': 'पासाडेना स्वास्थ्य केंद्र:',
      'ru': 'Центр здоровья Пасадены:',
      'sw': 'Kituo cha Afya cha Pasadena:',
      'vi': 'Trung tâm Y tế Pasadena:',
      'zh_Hans': '帕萨迪纳健康中心：',
    },
    'bhx6d61s': {
      'en': '(713) 893-5411\n',
      'ar': '(713) 893-5411',
      'es': '(713) 893-5411',
      'fr': '(713) 893-5411',
      'hi': '(713) 893-5411',
      'ru': '(713) 893-5411',
      'sw': '(713) 893-5411',
      'vi': '(713) 893-5411',
      'zh_Hans': '(713) 893-5411',
    },
    'vkp99f1v': {
      'en':
          'Accepts: Medicare, medicaid\n\nIncome: all incomes levels accepted \n\nFees: Sliding scale of fees based on income\n\nLanguages Spoken: Arabic, English, Spanish\n\nServices: Family Practice, Dental Services, OB/GYN Services, Pediatric Services, Counseling Services, Senior Adults, Internal Medicine\n\nHours: Monday-Friday 8am - 5pm\nSaturday: 8:30am - 12pm',
      'ar':
          'قبول: ميديكير ، ميديكيد الدخل: جميع مستويات الدخل المقبولة الرسوم: مقياس متدرج للرسوم على أساس الدخل اللغات المتحدث بها: العربية ، الإنجليزية ، الخدمات الإسبانية: ممارسة الأسرة ، خدمات طب الأسنان ، خدمات أمراض النساء والولادة ، خدمات طب الأطفال ، خدمات الاستشارة ، كبار السن ، ساعات الطب الباطني: الاثنين - الجمعة 8 ص - 5 م السبت: 8:30 ص - 12 م',
      'es':
          'Acepta: Medicare, Medicaid Ingresos: se aceptan todos los niveles de ingresos Tarifas: escala móvil de tarifas según los ingresos Idiomas hablados: árabe, inglés, español Servicios: medicina familiar, servicios dentales, servicios de obstetricia y ginecología, servicios pediátricos, servicios de asesoramiento, adultos mayores, Medicina Interna Horario: Lunes a Viernes 8am - 5pm Sábado: 8:30am - 12pm',
      'fr':
          'Accepte : Medicare, Medicaid Revenu : tous les niveaux de revenus acceptés Frais : Échelle dégressive des frais en fonction du revenu Langues parlées : arabe, anglais, espagnol Services : médecine familiale, services dentaires, services OB/GYN, services pédiatriques, services de conseil, adultes âgés, Horaires de médecine interne : du lundi au vendredi de 8h à 17h Samedi : de 8h30 à 12h',
      'hi':
          'स्वीकार करता है: मेडिकेयर, मेडिकेड आय: सभी आय स्तर स्वीकृत शुल्क: आय के आधार पर फीस का स्लाइडिंग स्केल बोली जाने वाली भाषाएं: अरबी, अंग्रेजी, स्पेनिश सेवाएं: पारिवारिक अभ्यास, दंत चिकित्सा सेवाएं, ओबी / जीवाईएन सेवाएं, बाल चिकित्सा सेवाएं, परामर्श सेवाएं, वरिष्ठ वयस्क, आंतरिक चिकित्सा घंटे: सोमवार-शुक्रवार सुबह 8 बजे - शाम 5 बजे शनिवार: सुबह 8:30 - दोपहर 12 बजे',
      'ru':
          'Принимаются: Medicare, Medicaid Доход: принимаются все уровни доходов Сборы: скользящая шкала сборов в зависимости от дохода Языки: арабский, английский, испанский Услуги: семейная практика, стоматологические услуги, акушерско-гинекологические услуги, педиатрические услуги, консультационные услуги, услуги для пожилых людей, Часы работы внутренней медицины: понедельник-пятница с 8:00 до 17:00, суббота: с 8:30 до 12:00.',
      'sw':
          'Hukubaliwa: Medicare, medicaid Mapato: viwango vyote vya mapato kukubaliwa Ada: Kiwango cha kutelezesha cha ada kulingana na mapato Lugha Zinazozungumzwa: Kiarabu, Kiingereza, Kihispania: Mazoezi ya Familia, Huduma za Meno, Huduma za OB/GYN, Huduma za Watoto, Huduma za Ushauri, Watu Wazima Wakuu, Masaa ya Dawa ya Ndani: Jumatatu-Ijumaa 8am - 5pm Jumamosi: 8:30am - 12pm',
      'vi':
          'Các chấp nhận: Medicare, dược thu Giờ khám nội khoa: Thứ Hai-Thứ Sáu, 8 giờ sáng - 5 giờ chiều Thứ Bảy: 8 giờ 30 sáng - 12 giờ trưa',
      'zh_Hans':
          '接受：医疗保险、医疗补助 收入：接受所有收入水平 费用：根据收入调整收费标准 语言：阿拉伯语、英语、西班牙语 服务：家庭诊所、牙科服务、妇产科服务、儿科服务、咨询服务、老年人、内科时间：周一至周五 8am - 5pm 周六：8:30am - 12pm',
    },
    'glre282s': {
      'en': '908 Southmore Ave Pasadena, TX - 77502\n',
      'ar': '908 ساوثمور افي باسادينا ، تكساس - 77502',
      'es': '908 Southmore Ave Pasadena, TX - 77502',
      'fr': '908, avenue Southmore Pasadena, Texas - 77502',
      'hi': '908 साउथमोर एवेन्यू पासाडेना, TX - 77502',
      'ru': '908 Southmore Ave Пасадена, Техас - 77502',
      'sw': '908 Southmore Ave Pasadena, TX - 77502',
      'vi': '908 Southmore Ave Pasadena, TX - 77502',
      'zh_Hans': '908 Southmore Ave 帕萨迪纳，TX - 77502',
    },
    '1metw3vu': {
      'en': 'Rate Center',
      'ar': 'مركز معدل',
      'es': 'Centro de tarifas',
      'fr': 'Centre tarifaire',
      'hi': 'दर केंद्र',
      'ru': 'Центр ставок',
      'sw': 'Kituo cha Viwango',
      'vi': 'Trung tâm tỷ giá',
      'zh_Hans': '费率中心',
    },
    'fnmpgk8x': {
      'en': 'View Rates',
      'ar': 'عرض الأسعار',
      'es': 'Ver tarifas',
      'fr': 'Voir les tarifs',
      'hi': 'दरें देखें',
      'ru': 'Посмотреть цены',
      'sw': 'Tazama Viwango',
      'vi': 'Xem biểu phí',
      'zh_Hans': '查看价格',
    },
    'c6tj2dd2': {
      'en': 'Select Clinic',
      'ar': 'حدد العيادة',
      'es': 'Seleccione Clínica',
      'fr': 'Sélectionnez la clinique',
      'hi': 'क्लिनिक का चयन करें',
      'ru': 'Выберите клинику',
      'sw': 'Chagua Kliniki',
      'vi': 'Chọn Phòng khám',
      'zh_Hans': '选择诊所',
    },
    '2rseceaf': {
      'en': 'Home',
      'ar': 'مسكن',
      'es': 'Casa',
      'fr': 'Domicile',
      'hi': 'घर',
      'ru': 'Дом',
      'sw': 'Nyumbani',
      'vi': 'Nhà',
      'zh_Hans': '家',
    },
  },
  // bookAppointment
  {
    'whlfp7qp': {
      'en': 'Book Appointment',
      'ar': 'موعد الكتاب',
      'es': 'Reservar una cita',
      'fr': 'Prendre rendez-vous',
      'hi': 'निर्धारित तारीख बुक करना',
      'ru': 'Записаться на прием',
      'sw': 'Uteuzi wa Kitabu',
      'vi': 'Đặt lịch hẹn',
      'zh_Hans': '预约',
    },
    's9ijazmg': {
      'en':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': 'املأ المعلومات أدناه من أجل حجز موعدك مع مكتبنا.',
      'es':
          'Complete la información a continuación para reservar su cita con nuestra oficina.',
      'fr':
          'Remplissez les informations ci-dessous afin de réserver votre rendez-vous avec notre bureau.',
      'hi':
          'हमारे कार्यालय में अपना अपॉइंटमेंट बुक करने के लिए नीचे दी गई जानकारी भरें।',
      'ru':
          'Заполните информацию ниже, чтобы записаться на прием в нашем офисе.',
      'sw': 'Jaza maelezo hapa chini ili uweke miadi yako na ofisi yetu.',
      'vi':
          'Điền vào thông tin dưới đây để đặt lịch hẹn của bạn với văn phòng của chúng tôi.',
      'zh_Hans': '填写以下信息，以便与我们的办公室预约。',
    },
    'l4nxc4ts': {
      'en': 'Emails will be sent to:',
      'ar': 'سيتم إرسال رسائل البريد الإلكتروني إلى:',
      'es': 'Los correos electrónicos serán enviados a:',
      'fr': 'Les e-mails seront envoyés à :',
      'hi': 'ईमेल यहां भेजे जाएंगे:',
      'ru': 'Электронные письма будут отправлены на:',
      'sw': 'Barua pepe zitatumwa kwa:',
      'vi': 'Email sẽ được gửi đến:',
      'zh_Hans': '电子邮件将发送至：',
    },
    'k6xddxff': {
      'en': 'Booking For',
      'ar': 'الحجز لـ',
      'es': 'reserva para',
      'fr': 'Réservation pour',
      'hi': 'बुकिंग के लिए',
      'ru': 'Бронирование для',
      'sw': 'Booking Kwa',
      'vi': 'Đặt trước cho',
      'zh_Hans': '预订',
    },
    'nuj9xng8': {
      'en': 'Type of Appointment',
      'ar': 'نوع التعيين',
      'es': 'Tipo de cita',
      'fr': 'Type de rendez-vous',
      'hi': 'नियुक्ति का प्रकार',
      'ru': 'Тип назначения',
      'sw': 'Aina ya Uteuzi',
      'vi': 'Loại cuộc hẹn',
      'zh_Hans': '约会类型',
    },
    'hln42jow': {
      'en': 'Doctors Visit',
      'ar': 'زيارة الأطباء',
      'es': 'Visita de médicos',
      'fr': 'Visite de médecins',
      'hi': 'डॉक्टरों का दौरा',
      'ru': 'Визит врачей',
      'sw': 'Kutembelea Madaktari',
      'vi': 'Khám bác sĩ',
      'zh_Hans': '医生来访',
    },
    'cgypzm0b': {
      'en': 'Routine Checkup',
      'ar': 'فحص روتيني حتى',
      'es': 'Exámenes de rutina',
      'fr': 'Vérification de routine',
      'hi': 'नियमित जाँच',
      'ru': 'Плановый осмотр',
      'sw': 'Ukaguzi wa Kawaida',
      'vi': 'Kiểm tra thường kỳ',
      'zh_Hans': '例行检查',
    },
    'o08s4k0f': {
      'en': 'Scan/Update',
      'ar': 'مسح / تحديث',
      'es': 'Escanear/Actualizar',
      'fr': 'Numériser/Mettre à jour',
      'hi': 'स्कैन/अपडेट',
      'ru': 'Сканировать/обновить',
      'sw': 'Changanua/Sasisha',
      'vi': 'Quét / Cập nhật',
      'zh_Hans': '扫描/更新',
    },
    '0ltec1jz': {
      'en': 'What\'s the problem?',
      'ar': 'ما هي المشكلة؟',
      'es': '¿Cuál es el problema?',
      'fr': 'Quel est le problème?',
      'hi': 'समस्या क्या है?',
      'ru': 'В чем проблема?',
      'sw': 'Tatizo ni nini?',
      'vi': 'Vấn đề là gì?',
      'zh_Hans': '有什么问题？',
    },
    'sax16jz6': {
      'en': 'Choose Date',
      'ar': 'اختر موعدا',
      'es': 'Elija Fecha',
      'fr': 'Choisissez la date',
      'hi': 'तिथि चुनें',
      'ru': 'Выберите дату',
      'sw': 'Chagua Tarehe',
      'vi': 'Chọn ngày',
      'zh_Hans': '选择日期',
    },
    'xoxu8pps': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'hi': 'रद्द करना',
      'ru': 'Отмена',
      'sw': 'Ghairi',
      'vi': 'Hủy bỏ',
      'zh_Hans': '取消',
    },
    'nz3x8he4': {
      'en': 'Book Now',
      'ar': 'احجز الآن',
      'es': 'Reservar ahora',
      'fr': 'Reserve maintenant',
      'hi': 'अभी बुक करें',
      'ru': 'Заказать сейчас',
      'sw': 'Weka Nafasi Sasa',
      'vi': 'Đặt bây giờ',
      'zh_Hans': '现在预订',
    },
  },
  // bookingOld
  {
    'jmy52497': {
      'en': 'Book Appointment',
      'ar': 'موعد الكتاب',
      'es': 'Reservar una cita',
      'fr': 'Prendre rendez-vous',
      'hi': 'निर्धारित तारीख बुक करना',
      'ru': 'Записаться на прием',
      'sw': 'Uteuzi wa Kitabu',
      'vi': 'Đặt lịch hẹn',
      'zh_Hans': '预约',
    },
    'q1sgo0s4': {
      'en':
          'Fill out the information below in order to book your appointment with our office.',
      'ar': 'املأ المعلومات أدناه من أجل حجز موعدك مع مكتبنا.',
      'es':
          'Complete la información a continuación para reservar su cita con nuestra oficina.',
      'fr':
          'Remplissez les informations ci-dessous afin de réserver votre rendez-vous avec notre bureau.',
      'hi':
          'हमारे कार्यालय में अपना अपॉइंटमेंट बुक करने के लिए नीचे दी गई जानकारी भरें।',
      'ru':
          'Заполните информацию ниже, чтобы записаться на прием в нашем офисе.',
      'sw': 'Jaza maelezo hapa chini ili uweke miadi yako na ofisi yetu.',
      'vi':
          'Điền vào thông tin dưới đây để đặt lịch hẹn của bạn với văn phòng của chúng tôi.',
      'zh_Hans': '填写以下信息，以便与我们的办公室预约。',
    },
    'kvqpt08y': {
      'en': 'Email Address',
      'ar': 'عنوان بريد الكتروني',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ru': 'Адрес электронной почты',
      'sw': 'Barua pepe',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    'xwa7ixd8': {
      'en': 'Booking For',
      'ar': 'الحجز لـ',
      'es': 'reserva para',
      'fr': 'Réservation pour',
      'hi': 'बुकिंग के लिए',
      'ru': 'Бронирование для',
      'sw': 'Booking Kwa',
      'vi': 'Đặt trước cho',
      'zh_Hans': '预订',
    },
    '3jbw5x2o': {
      'en': 'Type of Appointment',
      'ar': 'نوع التعيين',
      'es': 'Tipo de cita',
      'fr': 'Type de rendez-vous',
      'hi': 'नियुक्ति का प्रकार',
      'ru': 'Тип назначения',
      'sw': 'Aina ya Uteuzi',
      'vi': 'Loại cuộc hẹn',
      'zh_Hans': '约会类型',
    },
    'vll4d5w0': {
      'en': 'Doctors Visit',
      'ar': 'زيارة الأطباء',
      'es': 'Visita de médicos',
      'fr': 'Visite de médecins',
      'hi': 'डॉक्टरों का दौरा',
      'ru': 'Визит врачей',
      'sw': 'Kutembelea Madaktari',
      'vi': 'Khám bác sĩ',
      'zh_Hans': '医生来访',
    },
    'lt6yjyei': {
      'en': 'Routine Checkup',
      'ar': 'فحص روتيني حتى',
      'es': 'Exámenes de rutina',
      'fr': 'Vérification de routine',
      'hi': 'नियमित जाँच',
      'ru': 'Плановый осмотр',
      'sw': 'Ukaguzi wa Kawaida',
      'vi': 'Kiểm tra thường kỳ',
      'zh_Hans': '例行检查',
    },
    '7806tq32': {
      'en': 'Scan/Update',
      'ar': 'مسح / تحديث',
      'es': 'Escanear/Actualizar',
      'fr': 'Numériser/Mettre à jour',
      'hi': 'स्कैन/अपडेट',
      'ru': 'Сканировать/обновить',
      'sw': 'Changanua/Sasisha',
      'vi': 'Quét / Cập nhật',
      'zh_Hans': '扫描/更新',
    },
    'lbxdbi2c': {
      'en': 'What\'s the problem?',
      'ar': 'ما هي المشكلة؟',
      'es': '¿Cuál es el problema?',
      'fr': 'Quel est le problème?',
      'hi': 'समस्या क्या है?',
      'ru': 'В чем проблема?',
      'sw': 'Tatizo ni nini?',
      'vi': 'Vấn đề là gì?',
      'zh_Hans': '有什么问题？',
    },
    'dppqvzd8': {
      'en': 'Choose Date',
      'ar': 'اختر موعدا',
      'es': 'Elija Fecha',
      'fr': 'Choisissez la date',
      'hi': 'तिथि चुनें',
      'ru': 'Выберите дату',
      'sw': 'Chagua Tarehe',
      'vi': 'Chọn ngày',
      'zh_Hans': '选择日期',
    },
    '48yi2yah': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'hi': 'रद्द करना',
      'ru': 'Отмена',
      'sw': 'Ghairi',
      'vi': 'Hủy bỏ',
      'zh_Hans': '取消',
    },
    'lfa6i0b5': {
      'en': 'Book Now',
      'ar': 'احجز الآن',
      'es': 'Reservar ahora',
      'fr': 'Reserve maintenant',
      'hi': 'अभी बुक करें',
      'ru': 'Заказать сейчас',
      'sw': 'Weka Nafasi Sasa',
      'vi': 'Đặt bây giờ',
      'zh_Hans': '现在预订',
    },
  },
  // editBooking
  {
    'bk4al5ra': {
      'en': 'Edit Appointment',
      'ar': 'تحرير موعد',
      'es': 'Editar cita',
      'fr': 'Modifier le rendez-vous',
      'hi': 'अपॉइंटमेंट संपादित करें',
      'ru': 'Изменить встречу',
      'sw': 'Hariri Uteuzi',
      'vi': 'Chỉnh sửa cuộc hẹn',
      'zh_Hans': '编辑约会',
    },
    'px66dyo8': {
      'en': 'Edit the fields below in order to change your appointment.',
      'ar': 'قم بتحرير الحقول أدناه لتغيير موعدك.',
      'es': 'Edite los campos a continuación para cambiar su cita.',
      'fr':
          'Modifiez les champs ci-dessous afin de modifier votre rendez-vous.',
      'hi': 'अपना अपॉइंटमेंट बदलने के लिए नीचे दिए गए फ़ील्ड संपादित करें।',
      'ru': 'Отредактируйте поля ниже, чтобы изменить встречу.',
      'sw': 'Hariri sehemu zilizo hapa chini ili kubadilisha miadi yako.',
      'vi': 'Chỉnh sửa các trường bên dưới để thay đổi cuộc hẹn của bạn.',
      'zh_Hans': '编辑以下字段以更改您的约会。',
    },
    'en4mmn6w': {
      'en': 'Emails will be sent to:',
      'ar': 'سيتم إرسال رسائل البريد الإلكتروني إلى:',
      'es': 'Los correos electrónicos serán enviados a:',
      'fr': 'Les e-mails seront envoyés à :',
      'hi': 'ईमेल यहां भेजे जाएंगे:',
      'ru': 'Электронные письма будут отправлены на:',
      'sw': 'Barua pepe zitatumwa kwa:',
      'vi': 'Email sẽ được gửi đến:',
      'zh_Hans': '电子邮件将发送至：',
    },
    'wyvwci48': {
      'en': 'Booking For',
      'ar': 'الحجز لـ',
      'es': 'reserva para',
      'fr': 'Réservation pour',
      'hi': 'बुकिंग के लिए',
      'ru': 'Бронирование для',
      'sw': 'Booking Kwa',
      'vi': 'Đặt trước cho',
      'zh_Hans': '预订',
    },
    'oge1izsx': {
      'en': 'Type of Appointment',
      'ar': 'نوع التعيين',
      'es': 'Tipo de cita',
      'fr': 'Type de rendez-vous',
      'hi': 'नियुक्ति का प्रकार',
      'ru': 'Тип назначения',
      'sw': 'Aina ya Uteuzi',
      'vi': 'Loại cuộc hẹn',
      'zh_Hans': '约会类型',
    },
    '3955gk7u': {
      'en': 'Doctors Visit',
      'ar': 'زيارة الأطباء',
      'es': 'Visita de médicos',
      'fr': 'Visite de médecins',
      'hi': 'डॉक्टरों का दौरा',
      'ru': 'Визит врачей',
      'sw': 'Kutembelea Madaktari',
      'vi': 'Khám bác sĩ',
      'zh_Hans': '医生来访',
    },
    'v5xy8ih1': {
      'en': 'Routine Checkup',
      'ar': 'فحص روتيني حتى',
      'es': 'Exámenes de rutina',
      'fr': 'Vérification de routine',
      'hi': 'नियमित जाँच',
      'ru': 'Плановый осмотр',
      'sw': 'Ukaguzi wa Kawaida',
      'vi': 'Kiểm tra thường kỳ',
      'zh_Hans': '例行检查',
    },
    'rlkts1ut': {
      'en': 'Scan/Update',
      'ar': 'مسح / تحديث',
      'es': 'Escanear/Actualizar',
      'fr': 'Numériser/Mettre à jour',
      'hi': 'स्कैन/अपडेट',
      'ru': 'Сканировать/обновить',
      'sw': 'Changanua/Sasisha',
      'vi': 'Quét / Cập nhật',
      'zh_Hans': '扫描/更新',
    },
    'qbywbnja': {
      'en': 'What\'s the problem?',
      'ar': 'ما هي المشكلة؟',
      'es': '¿Cuál es el problema?',
      'fr': 'Quel est le problème?',
      'hi': 'समस्या क्या है?',
      'ru': 'В чем проблема?',
      'sw': 'Tatizo ni nini?',
      'vi': 'Vấn đề là gì?',
      'zh_Hans': '有什么问题？',
    },
    'foqhm35n': {
      'en': 'Choose Date',
      'ar': 'اختر موعدا',
      'es': 'Elija Fecha',
      'fr': 'Choisissez la date',
      'hi': 'तिथि चुनें',
      'ru': 'Выберите дату',
      'sw': 'Chagua Tarehe',
      'vi': 'Chọn ngày',
      'zh_Hans': '选择日期',
    },
    'aw794xw1': {
      'en': 'Cancel',
      'ar': 'يلغي',
      'es': 'Cancelar',
      'fr': 'Annuler',
      'hi': 'रद्द करना',
      'ru': 'Отмена',
      'sw': 'Ghairi',
      'vi': 'Hủy bỏ',
      'zh_Hans': '取消',
    },
    'zb4tp9kj': {
      'en': 'Save Changes',
      'ar': 'حفظ التغييرات',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ru': 'Сохранить изменения',
      'sw': 'Hifadhi mabadiliko',
      'vi': 'Lưu thay đổi',
      'zh_Hans': '保存更改',
    },
  },
  // Miscellaneous
  {
    'bfq7yvyf': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xwmmud0l': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '52ugcn2j': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'cw801z7r': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'we9zjify': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '99delvoc': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '9hhwg9q9': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rzzo16zq': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'c2h71cyx': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'mvk56yt5': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '29bretdz': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ylzj8zs0': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'iy3boonf': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '031e0gyu': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'y1srhnt6': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'x43qqnp9': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '6mtol5i9': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'cxchqgb7': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ulpk4zjb': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
    '5ocf5iuy': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ru': '',
      'sw': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
